-- 한줄 주석
/*
 * 	범위 주석
 */

CREATE TABLE TBL_MEMBER(
	NAME VARCHAR2(500),
	AGE NUMBER
);

DROP TABLE TBL_MEMBER;

-- 자동차 테이블 생성
-- 자동차 번호
-- 자동차 브랜드
-- 출시날짜
-- 색상
-- 가격

CREATE TABLE TBL_CAR(
	num NUMBER,
	brand VARCHAR2(1000),
	releaseDate DATE,
	color VARCHAR2(1000),
	price NUMBER(3)
);

ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(NUM);
ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;

DROP TABLE TBL_CAR;

--동물 테이블 생성
--	고유번호
--	종류
--	나이
--	먹이
CREATE TABLE TBL_ANIMAL(
	ID NUMBER /*PRIMARY KEY*/,
	"TYPE" VARCHAR2(1000),
	AGE NUMBER(3),
	FEED VARCHAR2(1000)
);

--제약조건 추가(PK)
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY(ID);

--제약조건 삭제(PK)
ALTER TABLE TBL_ANIMAL DROP CONSTRAINT PK_ANIMAL;

--컬럼 추가
ALTER TABLE TBL_ANIMAL ADD(GENDER CHAR(1));

--컬럼 이름 수정
ALTER TABLE TBL_ANIMAL RENAME COLUMN ID TO NUM;

--컬럼 삭제
ALTER TABLE TBL_ANIMAL DROP COLUMN GENDER;

--컬럼 수정
ALTER TABLE TBL_ANIMAL MODIFY(FEED VARCHAR2(2000));
ALTER TABLE TBL_ANIMAL MODIFY(FEED NUMBER);

--동물 테이블 삭제
DROP TABLE TBL_ANIMAL;

--학생 테이블 생성
--	학생 번호
--	학생 아이디
--	학생 이름
--	전공
--	성별-CHAR
--	생년월일
CREATE TABLE TBL_STUDENT(
	NUM NUMBER /*PRIMARY KEY*/,
	ID VARCHAR2(1000) /*UNIQUE*/,
	NAME VARCHAR2(500),
	MAJOR VARCHAR2(1000),
	GENDER CHAR(1) DEFAULT 'F' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER IN('M','F')),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD'))
);

--PK는 학생 번호로 설정한다.
ALTER TABLE TBL_STUDENT DROP CONSTRAINT SYS_C007003;
ALTER TABLE TBL_STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(NUM);

--컬럼 이름 수정
--	학생 아이디 이름을 수정해본다.
ALTER TABLE TBL_STUDENT RENAME COLUMN ID TO studentId;

--컬럼 추가
--	남친여친유무 컬럼 추가
ALTER TABLE TBL_STUDENT ADD(COUPLE CHAR(1));

-- 유니크 키 추가
--	학생 아이디를 유니크 키로 추가
ALTER TABLE TBL_STUDENT DROP CONSTRAINT SYS_C007004;
ALTER TABLE TBL_STUDENT ADD CONSTRAINT UK_STUDENT UNIQUE(studentId);

-- 학생 테이블 삭제
DROP TABLE TBL_STUDENT;


/*	FLOWER
	--------------------
	NAME : VARCHAR2(1000)
	--------------------
	COLOR : VARCHAR2(500)
	PRICE : NUMBER(10)


	POT
	--------------------
	NUM : NUMBER
	--------------------
	COLOR : VARCHAR2(500)
	SHAPE : VARCHAR2(1000)
	NAME : VARCHAR2(1000) : FK*/

CREATE TABLE TBL_FLOWER(
	NAME VARCHAR2(1000) PRIMARY KEY,
	COLOR VARCHAR2(500),
	PRICE NUMBER(10)
);

CREATE TABLE TBL_POT(
	NUM NUMBER PRIMARY KEY,
	COLOR VARCHAR2(500),
	SHAPE VARCHAR2(1000),
	NAME VARCHAR2(1000),
	CONSTRAINT FK_POT FOREIGN KEY(NAME) REFERENCES TBL_FLOWER(NAME)
);










