--시퀀스
--원하는 시작점을 설정하여 n씩 증가하는 값
--기본 시작점은 1이고 기본 증감량은 1이다.
CREATE SEQUENCE SEQ_USER
START WITH 2;

CREATE TABLE TBL_USER(
	userNumber NUMBER PRIMARY KEY,
	id VARCHAR2(1000) UNIQUE,
	pw VARCHAR2(1000),
	name VARCHAR2(1000),
	age NUMBER,
	phoneNumber VARCHAR2(100),
	status NUMBER
);

SELECT USERNUMBER, COUNT(USERNUMBER) FROM TBL_USER
WHERE ID = 'hds1234' AND PW = '1234'
GROUP BY USERNUMBER;

SELECT * FROM TBL_USER;

INSERT INTO TBL_USER
(USERNUMBER, ID, PW, NAME, AGE, PHONENUMBER, STATUS)
VALUES(SEQ_USER.NEXTVAL, 'hds2222', '2222', '한동석', 10, '01012341234', 0);

SELECT ID, STATUS FROM TBL_USER WHERE PHONENUMBER = '01012341234';















